import turtle
t = turtle.Pen()
t.shape('turtle')
t.color('black')
t.penup()
t.goto (100, 0)
t.left(90)
t.pendown()
t.fillcolor('yellow')
t.begin_fill()
t.circle(150)
t.end_fill()
t.penup()
t.goto(-90, 50)
t.pendown()
t.fillcolor('blue')
t.begin_fill()
t.circle(15)
t.end_fill()
t.penup()
t.goto(30, 50)
t.down()
t.fillcolor('blue')
t.begin_fill()
t.circle(15)
t.end_fill()
t.penup()
t.goto(-50, 30)
t.pendown()
t.color('black')
t.pensize(8)
t.left(180)
t.forward(50)
t.penup()
t.goto(20, -10)
t.color('red')
t.pendown()
t.circle(-70, 180, 30)